version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - D:/Workspace/sboot/project-sboot/bin:/sql_files
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
